# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.

      PIP_DEPENDENCIES: "tox"
      TOXENV: "test"

  matrix:
      - PYTHON_VERSION: "2.7"
      - PYTHON_VERSION: "3.4"
      - PYTHON_VERSION: "3.5"
      - PYTHON_VERSION: "3.6"
      - PYTHON_VERSION: "3.7"

platform:
    -x64

install:

    # Set up ci-helpers
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"

    # Some of the tests use git commands that require a user to be configured
    - git config --global user.name "A U Thor"
    - git config --global user.email "author@example.com"

    # For now we skip the installation of the graphviz package because the
    # graphviz.org website seems to be unresponsive intermittently, which
    # causes timeouts in downloads.
    - cinst graphviz.portable

build: false

test_script:
  - "%CMD_IN_ENV% tox -e %TOXENV%"
